FROM debian:buster-slim
RUN apt-get update && apt-get upgrade -y && apt-get install -y  ca-certificates libssl-dev libssl1.1
COPY target/release/swir-operator /swir-operator

ENV RUST_BACKTRACE=full
ENV RUST_LOG=info

ENTRYPOINT ["./swir-operator"]